name: Automated Validation

on: [push]

jobs:
  Sample-Run-of-Jekyll-Deploy-Test-Action:
    runs-on: ubuntu-latest
    name: This job tests the functionality of the Jekyll Deploy Test Action.
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Jekyll Deploy Test
      uses: PaulRosenthal/Jekyll-Deploy-Test-Action@v2
      with:
        gemfile-location: '/'
        site-directory: '/'
